version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins-master
    volumes:
      - jenkins:/var/jenkins_home
  proxy:
    image: shipyard/docker-proxy
    ports:
      - 3375:2375
    container_name: docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins:
